apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: httpd     
  namespace: shen-app  
spec:
  selector:
    matchExpressions:
      - key: app  
        operator: In
        values:
        - httpd 
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
