apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: httpd                           
  namespace: shen-app
  labels:
    app: httpd
  annotations:
    apps.open-cluster-management.io/github-branch:
    apps.open-cluster-management.io/github-path:
spec:
  channel:  shen-app/federation
  placement: 
    placementRef: 
      kind: PlacementRule
      name: local-cluster
